"""Ajout des tables groupes et promotions

Revision ID: f230aaa1b7f6
Revises: 
Create Date: 2026-03-10 10:08:47.108577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f230aaa1b7f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promotions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=50), nullable=False),
    sa.Column('annee_debut', sa.Integer(), nullable=True),
    sa.Column('annee_fin', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('groupes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=50), nullable=False),
    sa.Column('promotion_id', sa.Integer(), nullable=False),
    sa.Column('effectif', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    with op.batch_alter_table('salles', schema=None) as batch_op:
        batch_op.alter_column('nom',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('equipements',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salles', schema=None) as batch_op:
        batch_op.alter_column('equipements',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('nom',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)

    op.drop_table('groupes')
    op.drop_table('promotions')
    # ### end Alembic commands ###
